// Copyright 2021 Contributors to the Parsec project.
// SPDX-License-Identifier: Apache-2.0
#![allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    clippy::unseparated_literal_suffix,
    improper_ctypes,
    missing_debug_implementations,
    trivial_casts,
    clippy::all,
    unused
)]
// Suppress warnings from bindgen-generated code
// Remove on resolution of
// https://github.com/rust-lang/rust-bindgen/issues/1651
#![allow(deref_nullptr)]
///! This crate provides a basic interface for accessing the TSS Enhanced
///! System API from Rust. No abstraction is provided beyond what is
///! automatically generated by `bindgen` - the `tss-esapi` crate is the
///! one exposing an idiomatic Rust interface built on top of this FFI.

// For supported targets: use the generated and committed bindings.
#[cfg(all(
    not(feature = "generate-bindings"),
    target_arch = "x86_64",
    target_os = "linux"
))]
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/bindings/x86_64-unknown-linux-gnu.rs"
));

#[cfg(all(
    not(feature = "generate-bindings"),
    target_arch = "aarch64",
    target_os = "linux"
))]
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/bindings/aarch64-unknown-linux-gnu.rs"
));

#[cfg(all(
    not(feature = "generate-bindings"),
    target_arch = "arm",
    target_os = "linux"
))]
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/bindings/arm-unknown-linux-gnueabi.rs"
));

#[cfg(all(
    not(feature = "generate-bindings"),
    target_arch = "x86_64",
    target_os = "macos"
))]
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/bindings/x86_64-unknown-darwin.rs"
));

// If the "generate-bindings" feature is on, use the generated bindings.
#[cfg(feature = "generate-bindings")]
include!(concat!(env!("OUT_DIR"), "/tss_esapi_bindings.rs"));

// Tss2_Tcti_Device_Init is exposed by libtss2-tcti-device. The committed
// bindgen output doesn't include it because upstream tss-esapi-sys only
// links the loader-based path; we link tss2-tcti-device statically (see
// build.rs) and declare the symbol manually so we can bypass tctildr.
//
// Linux-only: `/dev/tpm0` and the device TCTI shared object only exist on
// Linux, and build.rs only pkg_config-probes tss2-tcti-device there.
//
// Use the binding-internal `size_t` (rather than Rust's `usize`) to match
// the rest of the generated TCTI init typedefs — the bindings are built
// with `size_t_is_usize(false)`, and on 32-bit ARM Linux size_t is c_uint
// rather than c_ulong, so the two aren't ABI-equivalent everywhere.
#[cfg(target_os = "linux")]
unsafe extern "C" {
    pub fn Tss2_Tcti_Device_Init(
        tctiContext: *mut TSS2_TCTI_CONTEXT,
        size: *mut size_t,
        conf: *const ::std::os::raw::c_char,
    ) -> TSS2_RC;
}
